# Generated by Django 4.2.16 on 2026-09-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Латинское название созвездия', max_length=100, unique=True, verbose_name='Название (лат.)')),
                ('name_ru', models.CharField(help_text='Русское название созвездия', max_length=100, verbose_name='Название (рус.)')),
                ('abbreviation', models.CharField(blank=True, help_text='Официальная аббревиатура (3 буквы)', max_length=10, verbose_name='Аббревиатура')),
                ('description', models.TextField(blank=True, help_text='Подробное описание созвездия', verbose_name='Описание')),
                ('area', models.FloatField(blank=True, help_text='Площадь созвездия в квадратных градусах', null=True, verbose_name='Площадь (кв.градусов)')),
                ('best_viewing_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Месяц наилучшей видимости (1-12)', null=True, verbose_name='Лучший месяц наблюдения')),
                ('is_zodiacal', models.BooleanField(default=False, help_text='Является ли созвездие зодиакальным', verbose_name='Зодиакальное')),
                ('is_visible_from_russia', models.BooleanField(default=True, help_text='Видимо ли с территории России', verbose_name='Видимо из России')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Созвездие',
                'verbose_name_plural': 'Созвездия',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='ConstellationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_from_name', models.CharField(max_length=100, verbose_name='Звезда (от)')),
                ('star_to_name', models.CharField(max_length=100, verbose_name='Звезда (до)')),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='constellations.constellation', verbose_name='Созвездие')),
            ],
            options={
                'verbose_name': 'Линия созвездия',
                'verbose_name_plural': 'Линии созвездий',
                'ordering': ['constellation'],
            },
        ),
    ]
