# Generated by Django 4.2.16 on 2026-09-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Общепринятое имя звезды (например, Бетельгейзе)', max_length=200, verbose_name='Название')),
                ('catalog_name', models.CharField(blank=True, help_text='Название по каталогу (например, α Ori)', max_length=200, verbose_name='Каталожное имя')),
                ('right_ascension', models.FloatField(blank=True, help_text='Прямое восхождение в часах (0-24)', null=True, verbose_name='Прямое восхождение')),
                ('declination', models.FloatField(blank=True, help_text='Склонение в градусах (-90 до +90)', null=True, verbose_name='Склонение')),
                ('apparent_magnitude', models.FloatField(blank=True, help_text='Чем меньше число, тем ярче звезда', null=True, verbose_name='Видимая звёздная величина')),
                ('absolute_magnitude', models.FloatField(blank=True, null=True, verbose_name='Абсолютная звёздная величина')),
                ('distance_ly', models.FloatField(blank=True, help_text='Расстояние в световых годах', null=True, verbose_name='Расстояние (св.лет)')),
                ('temperature', models.IntegerField(blank=True, help_text='Эффективная температура поверхности в Кельвинах', null=True, verbose_name='Температура (K)')),
                ('spectral_class', models.CharField(blank=True, choices=[('O', 'O — голубая (>30000K)'), ('B', 'B — голубовато-белая (10000-30000K)'), ('A', 'A — белая (7500-10000K)'), ('F', 'F — жёлто-белая (6000-7500K)'), ('G', 'G — жёлтая (5200-6000K)'), ('K', 'K — оранжевая (3700-5200K)'), ('M', 'M — красная (2400-3700K)')], max_length=1, verbose_name='Спектральный класс')),
                ('color_hex', models.CharField(default='#ffffff', help_text='HEX-код цвета звезды для отображения', max_length=7, verbose_name='Цвет (HEX)')),
                ('position_x', models.FloatField(default=0.5, help_text='Нормализованная координата X на карте', verbose_name='Позиция X (0-1)')),
                ('position_y', models.FloatField(default=0.5, help_text='Нормализованная координата Y на карте', verbose_name='Позиция Y (0-1)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_variable', models.BooleanField(default=False, verbose_name='Переменная звезда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='constellations.constellation', verbose_name='Созвездие')),
            ],
            options={
                'verbose_name': 'Звезда',
                'verbose_name_plural': 'Звёзды',
                'ordering': ['apparent_magnitude'],
                'indexes': [models.Index(fields=['constellation'], name='stars_star_constel_4acc8c_idx'), models.Index(fields=['spectral_class'], name='stars_star_spectra_7f57a1_idx'), models.Index(fields=['apparent_magnitude'], name='stars_star_apparen_87ddbf_idx')],
            },
        ),
    ]
